import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { createTRPCRouter, protectedProcedure } from "@/server/api/trpc";

export const vendorRouter = createTRPCRouter({
  // Get all vendors (excluding soft-deleted)
  getAll: protectedProcedure.query(async ({ ctx }) => {
    return await ctx.db.vendor.findMany({
      where: {
        deletedAt: null,
      },
      orderBy: {
        createdAt: "desc",
      },
      include: {
        gates: {
          include: {
            gate: true,
          },
        },
        zones: {
          include: {
            zone: true,
          },
        },
        _count: {
          select: {
            employees: true,
          },
        },
      },
    });
  }),

  // Get a single vendor by ID
  getById: protectedProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
        include: {
          gates: {
            include: {
              gate: true,
            },
          },
          zones: {
            include: {
              zone: true,
            },
          },
          employees: {
            where: {
              deletedAt: null,
            },
            include: {
              gates: {
                include: {
                  gate: true,
                },
              },
              zones: {
                include: {
                  zone: true,
                },
              },
            },
          },
          vendorAttachments: {
            include: {
              attachment: true,
            },
          },
        },
      });

      return vendor;
    }),

  // Create a new vendor
  create: protectedProcedure
    .input(
      z.object({
        name: z.string().min(1, "Name is required"),
        description: z.string().optional(),
        phoneNumber: z.string().optional(),
        allowedStaffCount: z
          .number()
          .min(1, "Must allow at least 1 staff member"),
        gateIds: z.array(z.string()).optional(),
        zoneIds: z.array(z.string()).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Validate gates exist if provided
      if (input.gateIds && input.gateIds.length > 0) {
        const gates = await ctx.db.gate.findMany({
          where: {
            id: { in: input.gateIds },
            deletedAt: null,
          },
        });
        if (gates.length !== input.gateIds.length) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "One or more selected gates not found",
          });
        }
      }

      // Validate zones exist if provided
      if (input.zoneIds && input.zoneIds.length > 0) {
        const zones = await ctx.db.zone.findMany({
          where: {
            id: { in: input.zoneIds },
            deletedAt: null,
          },
        });
        if (zones.length !== input.zoneIds.length) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "One or more selected zones not found",
          });
        }
      }

      const vendor = await ctx.db.vendor.create({
        data: {
          name: input.name,
          description: input.description,
          phoneNumber: input.phoneNumber,
          allowedStaffCount: input.allowedStaffCount,
          // accessToken is auto-generated by Prisma default
          gates: input.gateIds
            ? {
                create: input.gateIds.map((gateId) => ({
                  gateId,
                })),
              }
            : undefined,
          zones: input.zoneIds
            ? {
                create: input.zoneIds.map((zoneId) => ({
                  zoneId,
                })),
              }
            : undefined,
        },
        include: {
          gates: {
            include: {
              gate: true,
            },
          },
          zones: {
            include: {
              zone: true,
            },
          },
        },
      });

      return {
        success: true,
        vendor,
      };
    }),

  // Update a vendor
  update: protectedProcedure
    .input(
      z.object({
        id: z.string(),
        name: z.string().min(1, "Name is required"),
        description: z.string().optional(),
        phoneNumber: z.string().optional().nullable(),
        allowedStaffCount: z
          .number()
          .min(1, "Must allow at least 1 staff member"),
        gateIds: z.array(z.string()).optional(),
        zoneIds: z.array(z.string()).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Check if vendor exists
      const existingVendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!existingVendor || existingVendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      // Validate gates exist if provided
      if (input.gateIds && input.gateIds.length > 0) {
        const gates = await ctx.db.gate.findMany({
          where: {
            id: { in: input.gateIds },
            deletedAt: null,
          },
        });
        if (gates.length !== input.gateIds.length) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "One or more selected gates not found",
          });
        }
      }

      // Validate zones exist if provided
      if (input.zoneIds && input.zoneIds.length > 0) {
        const zones = await ctx.db.zone.findMany({
          where: {
            id: { in: input.zoneIds },
            deletedAt: null,
          },
        });
        if (zones.length !== input.zoneIds.length) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "One or more selected zones not found",
          });
        }
      }

      // Delete existing gate and zone relations
      await ctx.db.vendorGate.deleteMany({
        where: { vendorId: input.id },
      });
      await ctx.db.vendorZone.deleteMany({
        where: { vendorId: input.id },
      });

      const vendor = await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          name: input.name,
          description: input.description,
          phoneNumber: input.phoneNumber,
          allowedStaffCount: input.allowedStaffCount,
          gates: input.gateIds
            ? {
                create: input.gateIds.map((gateId) => ({
                  gateId,
                })),
              }
            : undefined,
          zones: input.zoneIds
            ? {
                create: input.zoneIds.map((zoneId) => ({
                  zoneId,
                })),
              }
            : undefined,
        },
        include: {
          gates: {
            include: {
              gate: true,
            },
          },
          zones: {
            include: {
              zone: true,
            },
          },
        },
      });

      return {
        success: true,
        vendor,
      };
    }),

  // Regenerate access token
  regenerateToken: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!vendor || vendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      // Generate new access token using Prisma's cuid()
      const { randomBytes } = await import("crypto");
      const newToken = randomBytes(16).toString("hex");

      const updatedVendor = await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          accessToken: newToken,
        },
      });

      return {
        success: true,
        accessToken: updatedVendor.accessToken,
      };
    }),

  // Soft delete a vendor
  delete: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!vendor || vendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          deletedAt: new Date(),
        },
      });

      return {
        success: true,
        message: "Vendor deleted successfully",
      };
    }),
});
