import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { createTRPCRouter, protectedProcedure } from "@/server/api/trpc";

export const vendorRouter = createTRPCRouter({
  // Get all vendors (excluding soft-deleted)
  getAll: protectedProcedure.query(async ({ ctx }) => {
    return await ctx.db.vendor.findMany({
      where: {
        deletedAt: null,
      },
      orderBy: {
        createdAt: "desc",
      },
      include: {
        gate: true,
        zone: true,
        _count: {
          select: {
            employees: true,
          },
        },
      },
    });
  }),

  // Get a single vendor by ID
  getById: protectedProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
        include: {
          gate: true,
          zone: true,
          employees: {
            where: {
              deletedAt: null,
            },
            include: {
              gate: true,
              zone: true,
            },
          },
          vendorAttachments: {
            include: {
              attachment: true,
            },
          },
        },
      });

      return vendor;
    }),

  // Create a new vendor
  create: protectedProcedure
    .input(
      z.object({
        name: z.string().min(1, "Name is required"),
        description: z.string().optional(),
        phoneNumber: z.string().optional(),
        allowedStaffCount: z
          .number()
          .min(1, "Must allow at least 1 staff member"),
        gateId: z.string().optional(),
        zoneId: z.string().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Validate gate exists if provided
      if (input.gateId) {
        const gate = await ctx.db.gate.findUnique({
          where: { id: input.gateId },
        });
        if (!gate || gate.deletedAt) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Selected gate not found",
          });
        }
      }

      // Validate zone exists if provided
      if (input.zoneId) {
        const zone = await ctx.db.zone.findUnique({
          where: { id: input.zoneId },
        });
        if (!zone || zone.deletedAt) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Selected zone not found",
          });
        }
      }

      const vendor = await ctx.db.vendor.create({
        data: {
          name: input.name,
          description: input.description,
          phoneNumber: input.phoneNumber,
          allowedStaffCount: input.allowedStaffCount,
          gateId: input.gateId,
          zoneId: input.zoneId,
          // accessToken is auto-generated by Prisma default
        },
        include: {
          gate: true,
          zone: true,
        },
      });

      return {
        success: true,
        vendor,
      };
    }),

  // Update a vendor
  update: protectedProcedure
    .input(
      z.object({
        id: z.string(),
        name: z.string().min(1, "Name is required"),
        description: z.string().optional(),
        phoneNumber: z.string().optional().nullable(),
        allowedStaffCount: z
          .number()
          .min(1, "Must allow at least 1 staff member"),
        gateId: z.string().optional().nullable(),
        zoneId: z.string().optional().nullable(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Check if vendor exists
      const existingVendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!existingVendor || existingVendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      // Validate gate exists if provided
      if (input.gateId) {
        const gate = await ctx.db.gate.findUnique({
          where: { id: input.gateId },
        });
        if (!gate || gate.deletedAt) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Selected gate not found",
          });
        }
      }

      // Validate zone exists if provided
      if (input.zoneId) {
        const zone = await ctx.db.zone.findUnique({
          where: { id: input.zoneId },
        });
        if (!zone || zone.deletedAt) {
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Selected zone not found",
          });
        }
      }

      const vendor = await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          name: input.name,
          description: input.description,
          phoneNumber: input.phoneNumber,
          allowedStaffCount: input.allowedStaffCount,
          gateId: input.gateId,
          zoneId: input.zoneId,
        },
        include: {
          gate: true,
          zone: true,
        },
      });

      return {
        success: true,
        vendor,
      };
    }),

  // Regenerate access token
  regenerateToken: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!vendor || vendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      // Generate new access token using Prisma's cuid()
      const { randomBytes } = await import("crypto");
      const newToken = randomBytes(16).toString("hex");

      const updatedVendor = await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          accessToken: newToken,
        },
      });

      return {
        success: true,
        accessToken: updatedVendor.accessToken,
      };
    }),

  // Soft delete a vendor
  delete: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const vendor = await ctx.db.vendor.findUnique({
        where: { id: input.id },
      });

      if (!vendor || vendor.deletedAt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Vendor not found",
        });
      }

      await ctx.db.vendor.update({
        where: { id: input.id },
        data: {
          deletedAt: new Date(),
        },
      });

      return {
        success: true,
        message: "Vendor deleted successfully",
      };
    }),
});
